site_name: "Terraform GitHub Actions"
site_description: Documentation for Terraform GitHub Actions
repo_url: https://github.com/POps-Rox/tf-gh-actions
edit_uri: edit/main/docs/

nav:
  - Home: index.md

plugins:
  - techdocs-core

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
